spring.application.name=deepright
## Redis Config
spring.data.redis.host=${REDIS_DATA_HOST:localhost}
spring.data.redis.port=${REDIS_DATA_PORT:6379}
spring.data.redis.timeout=10000ms
spring.data.redis.lettuce.shutdown-timeout=10000ms
spring.data.redis.lettuce.pool.max-wait=5000ms
spring.data.redis.lettuce.pool.max-active=1000
spring.data.redis.lettuce.pool.max-idle=1000
spring.data.redis.lettuce.pool.min-idle=1000
pubsub.redis.event.host=${REDIS_EVENT_HOST:localhost}
pubsub.redis.event.port=${REDIS_EVENT_PORT:6379}
pubsub.redis.event.lettuce.shutdown-timeout=10000ms
pubsub.redis.event.lettuce.pool.max-wait=5000ms
pubsub.redis.event.lettuce.pool.max-active=1000
pubsub.redis.event.lettuce.pool.max-idle=1000
pubsub.redis.event.lettuce.pool.min-idle=1000
pubsub.redis.event.timeout=10000ms
embedded.redis.enable=${EMBEDDED_REDIS_ENABLE:true}
## Framework
###### Netty
chat.http.request.max=30720000
chat.http.cors.enable=true
chat.http.idle.write=240
###### Provider LLM Config
request.provider.retry=3
request.provider=vertex
vertex.token.exchange.app.id=7b6c9e2a1f2e4d3c8b7a6f5e4d3c2b1a
vertex.token.uri=classpath:/key/service-account.enc
vertex.token.key=classpath:/key/private.pem
vertex.project.id=ai-life-456302
vertex.model=gemini-3.5-
anthropic.model.max_tokens=128000
anthropic.enable=true
bigmodel.enable=true
deepseek.enable=true
minimax.model.max_tokens=128000
minimax.enable=true
openai.enable=true
vertex.enable=true
gemini.enable=true
xiaomi.enable=true
kimi.enable=true
qwen.enable=true
###### Master wait funcall less than 24H
###### Each Funcall less than 15m
httpclient.timeout.stream.socket=60000
request.timeout.rate=50
funcall.waiting=172800000
funcall.timeout=86400000
request.maxSize=2048000
request.timeout=360000
deepness.max=500
###### Prompt
prompt.file.suffix=.md
###### Jar, JAR resource release
resource.release=true
###### Summary
summary.store.name=file.store.sys
summary.itemSize=100
###### FileStore
chat.http.host=${CHAT_HTTP_HOST:http://replace_host.com}
chat.http.port=${CHAT_HTTP_PORT:9998}
file.store.sys.expired=3600000
###### Feature Enable
event.listener.enable=true
placeholder.enable=true
rateLimit.enable=true
feedback.enable=true
function.enable=true
extreme.enable=true
trigger.enable=true
history.enable=true
passage.enable=true
schema.enable=true
skills.enable=true
block.enable=true
media.enable=true
token.enable=true
file.enable=true
## Json Config
cli.sub.timeout=300
task.timeout=1800
## LLM
llm.clientHistories=false
llm.storeCompleted=false
llm.recallOffset=900000
llm.recallNums=50
llm.histories=100
llm.scene=deepright@memory_main
## Any Gen
image_gen.networkBuffer=2097152
image_gen.aspectRatio=16:9
image_gen.timeout=480000
image_gen.imageSize=2k
file_gen.maxsize=26214400
file_gen.minsize=10240
file_gen.timeout=120000
ocr_gen.timeout=120000
## Memory & Summary
memory.summary.timeout=300000
memory.refresh.timeout=300000
summary.compress.timeout=300000
## Other
autodump.llm=autodump
## Auth
auth.target.provider=vertex
auth.source.token=12345
auth.target.token=
## Debug
debug=true
